# Generated by Django 6.0.1 on 2026-02-13 04:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(default='お客様', max_length=100, verbose_name='お名前')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='注文日時')),
                ('total_price', models.IntegerField(default=0, verbose_name='合計金額')),
                ('is_completed', models.BooleanField(default=False, verbose_name='提供済み')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='商品名')),
                ('description', models.TextField(blank=True, null=True, verbose_name='説明')),
                ('price', models.IntegerField(verbose_name='価格')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='商品画像')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='個数')),
                ('price', models.IntegerField(verbose_name='購入時の価格')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='商品')),
            ],
        ),
    ]
