# Generated by Django 6.0.2 on 2026-02-06 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sauce',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_sauce_customizable',
        ),
    ]
