# Generated by Django 6.0.1 on 2026-03-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('waffle', 'ワッフル'), ('drink', 'ドリンク')], default='waffle', max_length=20, verbose_name='カテゴリ'),
        ),
    ]
