# Generated by Django 6.0.2 on 2026-02-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_served',
            field=models.BooleanField(default=False, verbose_name='提供済み'),
        ),
    ]
