# Generated by Django 6.0.1 on 2026-03-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_session_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='session_key',
        ),
        migrations.AddField(
            model_name='order',
            name='device_id',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='デバイスID'),
        ),
    ]
