# Generated by Django 6.0.1 on 2026-03-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_order_session_key_order_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='temperature',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='温度'),
        ),
        migrations.AddField(
            model_name='product',
            name='temperature_option',
            field=models.CharField(choices=[('none', '選択なし'), ('both', 'ホット・アイス'), ('hot', 'ホットのみ'), ('ice', 'アイスのみ')], default='none', max_length=10, verbose_name='温度オプション'),
        ),
    ]
